spring:
  datasource:
    username: root
    password: qwe123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1:3306/webapp?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    #schema:
    #- classpath:sql/department.sql
    #- classpath:sql/employee.sql
    #spring2.0后要加上这个配置schema才生效,表示始终执行初始化
    initialization-mode: ALWAYS
    type: com.alibaba.druid.pool.DruidDataSource

    #==========数据源其他配置==========
    #初始化数量
    initialSize: 5
    #允许的最小空闲连接数
    minIdle: 5
    #最大活跃数
    maxActive: 20
    #最大连接等待超时时间，单位是毫秒(ms)
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #验证数据库连接的查询语句，这个查询语句必须是至少返回一条数据的SELECT语句
    validationQuery: SELECT 1
    #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    
  #thymeleaf 配置
  thymeleaf:
    #模板的模式，支持HTML, XML 、TEXT 、JAVASCRIPT 等
    mode: HTML5
    #编码， 可不用配置
    encoding: UTF-8
    #开发配置为false ，避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates ，可以不用配置
    prefix: classpath:/templates/
  messages:
    basename: i18n.messages
  
  #redis 缓存配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password: qwe123
    timeout: 1000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
#mybatis配置
mybatis:
  mapper-locations: classpath:/mappers/**/*Mapper.xml
  type-aliases-package: com.xyzq.webapp.entity.**
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#log4j配置
logging:
  config: classpath:log4j2.xml
